name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  check-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-versions.outputs.matrix }}
    
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Create version checker script
      run: |
        mkdir -p scripts
        cat > scripts/version_checker.py << 'EOL'
        import os
        import requests
        from bs4 import BeautifulSoup
        from requests.adapters import HTTPAdapter
        from requests.packages.urllib3.util.retry import Retry

        def fetch_url(url):
            session = requests.Session()
            retries = Retry(total=3, backoff_factor=1, status_forcelist=[500, 502, 503, 504])
            session.mount("https://", HTTPAdapter(max_retries=retries))
            response = session.get(url, timeout=10)
            response.raise_for_status()
            return response

        def extract_versions(soup, stable_label, mainline_label, prefix):
            versions = {"stable": None, "mainline": None}
            for tag in soup.find_all(["strong", "h4"]):
                text = tag.get_text(strip=True).lower()
                if stable_label in text:
                    table_or_next = tag.find_next(["a", "table"])
                    if table_or_next:
                        version_link = table_or_next.find("a", href=True, string=lambda s: s and prefix in s)
                        if version_link:
                            versions["stable"] = version_link.string.split('-')[1].strip('.tar.gz')
                elif mainline_label in text:
                    table_or_next = tag.find_next(["a", "table"])
                    if table_or_next:
                        version_link = table_or_next.find("a", href=True, string=lambda s: s and prefix in s)
                        if version_link:
                            versions["mainline"] = version_link.string.split('-')[1].strip('.tar.gz')
            return versions

        def get_nginx_versions():
            url = "https://nginx.org/en/download.html"
            try:
                print(f"Fetching {url}...")
                response = fetch_url(url)
            except requests.RequestException as e:
                print(f"Error fetching {url}: {e}")
                return {"stable": None, "mainline": None}

            soup = BeautifulSoup(response.text, 'html.parser')
            return extract_versions(soup, "stable version", "mainline version", "nginx-")

        def get_freenginx_versions():
            url = "https://freenginx.org/en/download.html"
            try:
                print(f"Fetching {url}...")
                response = fetch_url(url)
            except requests.RequestException as e:
                print(f"Error fetching {url}: {e}")
                return {"stable": None, "mainline": None}

            soup = BeautifulSoup(response.text, 'html.parser')
            return extract_versions(soup, "stable version", "mainline version", "freenginx-")

        def main():
            nginx_versions = get_nginx_versions()
            freenginx_versions = get_freenginx_versions()

            versions = []
            if nginx_versions['stable']:
                versions.append(f"nginx-{nginx_versions['stable']}")
            if nginx_versions['mainline']:
                versions.append(f"nginx-{nginx_versions['mainline']}")
            if freenginx_versions['stable']:
                versions.append(f"freenginx-{freenginx_versions['stable']}")
            if freenginx_versions['mainline']:
                versions.append(f"freenginx-{freenginx_versions['mainline']}")

            print(f"::set-output name=matrix::{versions}")

        if __name__ == "__main__":
            main()
        EOL

    - name: Get latest versions
      id: get-versions
      run: python scripts/version_checker.py

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpcre3-dev zlib1g-dev libssl-dev check

    - name: Run unit tests
      run: |
        cd tests/unit
        gcc -o test_module test_module.c -I. -lcheck -lpthread -lrt -lm -lsubunit
        ./test_module

  integration-tests:
    needs: [check-versions]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.check-versions.outputs.matrix) }}
        config: [
          'default',
          'debug',
          'with-threads',
          'with-http_ssl_module'
        ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpcre3-dev zlib1g-dev libssl-dev python3-pytest python3-requests nginx curl

    - name: Parse version info
      id: parse
      shell: bash
      run: |
        version="${{ matrix.version }}"
        type=$(echo "$version" | cut -d'-' -f1)
        ver=$(echo "$version" | cut -d'-' -f2)
        echo "TYPE=$type" >> "$GITHUB_OUTPUT"
        echo "VERSION=$ver" >> "$GITHUB_OUTPUT"

    - name: Download and Extract
      id: download
      run: |
        if [ "${{ steps.parse.outputs.TYPE }}" = "nginx" ]; then
          wget https://nginx.org/download/nginx-${{ steps.parse.outputs.VERSION }}.tar.gz
          tar -xzf nginx-${{ steps.parse.outputs.VERSION }}.tar.gz
          BUILD_DIR="nginx-${{ steps.parse.outputs.VERSION }}"
        else
          wget https://freenginx.org/download/freenginx-${{ steps.parse.outputs.VERSION }}.tar.gz
          tar -xzf freenginx-${{ steps.parse.outputs.VERSION }}.tar.gz
          BUILD_DIR="freenginx-${{ steps.parse.outputs.VERSION }}"
        fi
        echo "BUILD_DIR=$BUILD_DIR" >> "$GITHUB_OUTPUT"

    - name: Build and Test Module
      env:
        MODULE_PATH: ${{ github.workspace }}/${{ steps.download.outputs.BUILD_DIR }}/objs/ngx_http_upstream_mgmt_module.so
      run: |
        cd "${{ steps.download.outputs.BUILD_DIR }}"
        mkdir -p objs
        
        # Configure and build
        CONFIG_OPTS="--add-dynamic-module=../ --prefix=$(pwd)/install"
        case "${{ matrix.config }}" in
          debug)
            CONFIG_OPTS="$CONFIG_OPTS --with-debug"
            ;;
          with-threads)
            CONFIG_OPTS="$CONFIG_OPTS --with-threads"
            ;;
          with-http_ssl_module)
            CONFIG_OPTS="$CONFIG_OPTS --with-http_ssl_module"
            ;;
        esac
        
        echo "Running ./configure $CONFIG_OPTS"
        ./configure $CONFIG_OPTS
        make
        make install
        
        # Verify module was builtq
        echo "Checking built module:"
        ls -l objs/ngx_http_upstream_mgmt_module.so
        file objs/ngx_http_upstream_mgmt_module.so
        
        # Set path to our custom-built nginx
        NGINX_BIN=$(pwd)/install/sbin/nginx
        chmod +x $NGINX_BIN
        
        # Run integration tests
        cd ..
        echo "Using module at: ${MODULE_PATH}"
        echo "Using nginx binary at: ${NGINX_BIN}"
        cd tests/integration
        PYTHONPATH=. NGINX_BIN="${NGINX_BIN}" python3 -m pytest -v test_upstream_mgmt.py --log-cli-level=DEBUG

  cross-platform:
    needs: [check-versions]
    strategy:
      matrix:
        config:
          - os: 'ubuntu-2204'
            container: 'ubuntu:22.04'
          - os: 'ubuntu-2004'
            container: 'ubuntu:20.04'
          - os: 'debian-bullseye'
            container: 'debian:bullseye'
          - os: 'debian-bookworm'
            container: 'debian:bookworm'
          - os: 'fedora-latest'
            container: 'fedora:latest'
          - os: 'centos-7'
            container: 'quay.io/centos/centos:7'
            use_composite: true
          - os: 'rocky-8'
            container: 'quay.io/rockylinux/rockylinux:8'
            use_composite: true
      fail-fast: false

    runs-on: ${{ matrix.config.use_composite && 'ubuntu-20.04' || 'ubuntu-latest' }}
    container: ${{ !matrix.config.use_composite && matrix.config.container || '' }}

    steps:
    - uses: actions/checkout@v3

    - name: Get version from check-versions
      id: get-version
      run: |
        echo "Matrix output: ${{ needs.check-versions.outputs.matrix }}"
        # Clean and extract the first version string
        FIRST_VERSION=$(echo '${{ needs.check-versions.outputs.matrix }}' | tr -d '[]"' | cut -d',' -f1)
        echo "First version: $FIRST_VERSION"
        echo "VERSION=$FIRST_VERSION" >> $GITHUB_OUTPUT

    - name: Install basic tools (Debian/Ubuntu)
      if: contains(matrix.config.container, 'ubuntu') || contains(matrix.config.container, 'debian')
      shell: bash
      run: |
        apt-get update
        apt-get install -y wget

    - name: Install basic tools (Fedora)
      if: contains(matrix.config.container, 'fedora')
      shell: bash
      run: |
        dnf install -y wget

    - name: Parse version info
      id: parse
      shell: bash
      run: |
        set -x  # Enable debug output
        version="${{ steps.get-version.outputs.VERSION }}"
        echo "Full version string: $version"
        type=$(echo "$version" | cut -d'-' -f1)
        ver=$(echo "$version" | cut -d'-' -f2)
        # Debug output
        echo "Raw version: $version"
        echo "Parsed type: $type"
        echo "Parsed version: $ver"
        {
          echo "TYPE=$type"
          echo "VERSION=$ver"
          echo "BUILD_DIR=${type}-${ver}"
        } >> "$GITHUB_OUTPUT"

    - name: Setup and Build in RHEL-based systems
      if: matrix.config.use_composite
      run: |
        echo "Type: ${{ steps.parse.outputs.TYPE }}"
        echo "Version: ${{ steps.parse.outputs.VERSION }}"
        echo "Build dir: ${{ steps.parse.outputs.BUILD_DIR }}"
        
        docker run --rm \
          -v ${{ github.workspace }}:/github/workspace \
          -w /github/workspace \
          ${{ matrix.config.container }} \
          bash -c '
            set -ex
            
            # Detect OS and setup repositories
            if [ -f /etc/rocky-release ]; then
              dnf install -y dnf-plugins-core
              dnf config-manager --set-enabled powertools
            elif [ -f /etc/centos-release ]; then
              sed -i "s/mirrorlist/#mirrorlist/g" /etc/yum.repos.d/CentOS-*
              sed -i "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*
            fi
            
            # Install dependencies based on package manager
            if command -v yum &> /dev/null; then
              yum install -y gcc make pcre-devel zlib-devel openssl-devel wget file
            else
              dnf install -y gcc make pcre-devel zlib-devel openssl-devel wget file
            fi
            
            TYPE="${{ steps.parse.outputs.TYPE }}"
            VERSION="${{ steps.parse.outputs.VERSION }}"
            # Clean up version string (remove any spaces or commas)
            VERSION=$(echo "$VERSION" | tr -d " ," | tr -d "\n")
            echo "Building for type: $TYPE version: $VERSION"
            
            if [ "$TYPE" = "nginx" ]; then
              wget --no-verbose "https://nginx.org/download/nginx-${VERSION}.tar.gz"
              tar -xzf "nginx-${VERSION}.tar.gz"
              cd "nginx-${VERSION}"
            else
              wget --no-verbose "https://freenginx.org/download/freenginx-${VERSION}.tar.gz"
              tar -xzf "freenginx-${VERSION}.tar.gz"
              cd "freenginx-${VERSION}"
            fi
            
            ./configure --with-compat --add-dynamic-module=../
            make modules
            ls -l objs/*.so
            file objs/*.so'

    - name: Install build dependencies (Debian/Ubuntu)
      if: contains(matrix.config.container, 'ubuntu') || contains(matrix.config.container, 'debian')
      shell: bash
      run: |
        apt-get update
        apt-get install -y build-essential libpcre3-dev zlib1g-dev libssl-dev wget gcc make file

    - name: Install build dependencies (Fedora)
      if: contains(matrix.config.container, 'fedora')
      shell: bash
      run: |
        dnf install -y gcc make pcre-devel zlib-devel openssl-devel wget file

    - name: Download and Extract
      id: download
      if: "!matrix.config.use_composite"
      shell: bash
      run: |
        TYPE="${{ steps.parse.outputs.TYPE }}"
        VERSION="${{ steps.parse.outputs.VERSION }}"
        if [ -z "$TYPE" ] || [ -z "$VERSION" ]; then
          echo "Error: Missing type or version"
          echo "TYPE: '$TYPE'"
          echo "VERSION: '$VERSION'"
          exit 1
        fi
        echo "Building for type: $TYPE version: $VERSION"
        BUILD_DIR="${TYPE}-${VERSION}"
        echo "BUILD_DIR=$BUILD_DIR" >> "$GITHUB_OUTPUT"
        
        if [ "$TYPE" = "nginx" ]; then
          wget --no-verbose "https://nginx.org/download/${BUILD_DIR}.tar.gz"
          tar -xzf "${BUILD_DIR}.tar.gz"
        else
          wget --no-verbose "https://freenginx.org/download/${BUILD_DIR}.tar.gz"
          tar -xzf "${BUILD_DIR}.tar.gz"
        fi
        
        # Verify directory exists
        if [ ! -d "$BUILD_DIR" ]; then
          echo "Error: Build directory $BUILD_DIR not found after extraction"
          ls -la
          exit 1
        fi

    - name: Build Module
      if: "!matrix.config.use_composite"
      shell: bash
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        BUILD_DIR="${{ steps.download.outputs.BUILD_DIR }}"
        echo "Using build directory: $BUILD_DIR"
        cd "$BUILD_DIR" || exit 1
        echo "Entered directory: $(pwd)"
        ls -la
        ./configure --with-compat --add-dynamic-module=../
        make modules
        ls -l objs/*.so
        file objs/*.so

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.config.os }}-modules
        path: |
          ${{ github.workspace }}/${{ steps.parse.outputs.BUILD_DIR }}/objs/*.so
          ${{ github.workspace }}/${{ steps.parse.outputs.BUILD_DIR }}/objs/*.a
        if-no-files-found: warn
    
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpcre3-dev zlib1g-dev libssl-dev

    - name: Get latest stable Nginx version
      run: |
        STABLE_VERSION=$(curl -s https://nginx.org/en/download.html | grep -oP 'nginx-\K[0-9]+\.[0-9]+\.[0-9]+(?=\.tar\.gz)' | head -1)
        echo "NGINX_VERSION=$STABLE_VERSION" >> $GITHUB_ENV

    - name: Download Nginx for build
      run: |
        wget https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
        tar -xzf nginx-${NGINX_VERSION}.tar.gz

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: cpp

    - name: Build with configure
      run: |
        BUILD_DIR="nginx-${NGINX_VERSION}"
        cd $BUILD_DIR
        ./configure --with-compat --add-dynamic-module=../
        make modules

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:cpp"

  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check Documentation
      run: |
        if [ ! -f "README.md" ]; then
          echo "README.md is missing"
          exit 1
        fi