name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly to check against new nginx versions

jobs:
  check-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-versions.outputs.matrix }}
    
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Create version checker script
      run: |
        mkdir -p scripts
        cat > scripts/version_checker.py << 'EOL'
        import os
        import requests
        from bs4 import BeautifulSoup
        from requests.adapters import HTTPAdapter
        from requests.packages.urllib3.util.retry import Retry

        def fetch_url(url):
            session = requests.Session()
            retries = Retry(total=3, backoff_factor=1, status_forcelist=[500, 502, 503, 504])
            session.mount("https://", HTTPAdapter(max_retries=retries))
            response = session.get(url, timeout=10)
            response.raise_for_status()
            return response

        def extract_versions(soup, stable_label, mainline_label, prefix):
            versions = {"stable": None, "mainline": None}
            for tag in soup.find_all(["strong", "h4"]):
                text = tag.get_text(strip=True).lower()
                if stable_label in text:
                    table_or_next = tag.find_next(["a", "table"])
                    if table_or_next:
                        version_link = table_or_next.find("a", href=True, string=lambda s: s and prefix in s)
                        if version_link:
                            versions["stable"] = version_link.string.split('-')[1].strip('.tar.gz')
                elif mainline_label in text:
                    table_or_next = tag.find_next(["a", "table"])
                    if table_or_next:
                        version_link = table_or_next.find("a", href=True, string=lambda s: s and prefix in s)
                        if version_link:
                            versions["mainline"] = version_link.string.split('-')[1].strip('.tar.gz')
            return versions

        def get_nginx_versions():
            url = "https://nginx.org/en/download.html"
            try:
                print(f"Fetching {url}...")
                response = fetch_url(url)
            except requests.RequestException as e:
                print(f"Error fetching {url}: {e}")
                return {"stable": None, "mainline": None}

            soup = BeautifulSoup(response.text, 'html.parser')
            return extract_versions(soup, "stable version", "mainline version", "nginx-")

        def get_freenginx_versions():
            url = "https://freenginx.org/en/download.html"
            try:
                print(f"Fetching {url}...")
                response = fetch_url(url)
            except requests.RequestException as e:
                print(f"Error fetching {url}: {e}")
                return {"stable": None, "mainline": None}

            soup = BeautifulSoup(response.text, 'html.parser')
            return extract_versions(soup, "stable version", "mainline version", "freenginx-")

        def main():
            nginx_versions = get_nginx_versions()
            freenginx_versions = get_freenginx_versions()

            versions = []
            if nginx_versions['stable']:
                versions.append(f"nginx-{nginx_versions['stable']}")
            if nginx_versions['mainline']:
                versions.append(f"nginx-{nginx_versions['mainline']}")
            if freenginx_versions['stable']:
                versions.append(f"freenginx-{freenginx_versions['stable']}")
            if freenginx_versions['mainline']:
                versions.append(f"freenginx-{freenginx_versions['mainline']}")

            print(f"::set-output name=matrix::{versions}")

        if __name__ == "__main__":
            main()
        EOL

    - name: Get latest versions
      id: get-versions
      run: python scripts/version_checker.py

  build:
    needs: check-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.check-versions.outputs.matrix) }}
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpcre3-dev zlib1g-dev libssl-dev

    - name: Parse version info
      id: parse
      run: |
        IFS=- read -r type version <<< "${{ matrix.version }}"
        echo "TYPE=$type" >> $GITHUB_OUTPUT
        echo "VERSION=$version" >> $GITHUB_OUTPUT

    - name: Download and Extract
      run: |
        if [[ "${{ steps.parse.outputs.TYPE }}" == "nginx" ]]; then
          wget https://nginx.org/download/nginx-${{ steps.parse.outputs.VERSION }}.tar.gz
          tar -xzf nginx-${{ steps.parse.outputs.VERSION }}.tar.gz
        else
          wget https://freenginx.org/download/freenginx-${{ steps.parse.outputs.VERSION }}.tar.gz
          tar -xzf freenginx-${{ steps.parse.outputs.VERSION }}.tar.gz
        fi

    - name: Static Code Analysis
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --suppress=missingInclude .

    - name: Build Module
      run: |
        BUILD_DIR="${{ steps.parse.outputs.TYPE }}-${{ steps.parse.outputs.VERSION }}"
        cd $BUILD_DIR
        ./configure --with-compat --add-dynamic-module=../
        make modules

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.version }}-modules
        path: ${{ steps.parse.outputs.TYPE }}-${{ steps.parse.outputs.VERSION }}/objs/*.so

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v2
      with:
        languages: cpp

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  style-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Check Code Style
      run: |
        find . -name '*.c' -o -name '*.h' | xargs clang-format -style=file -n -Werror

  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check Documentation
      run: |
        if [ ! -f "README.md" ]; then
          echo "README.md is missing"
          exit 1
        fi