name: Quick Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quick-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4

    - name: Validate module files
      run: |
        chmod +x scripts/validate_build.sh
        ./scripts/validate_build.sh

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpcre3-dev zlib1g-dev libssl-dev

    - name: Download nginx
      run: |
        wget https://nginx.org/download/nginx-1.26.2.tar.gz
        tar -xzf nginx-1.26.2.tar.gz

    - name: Build module
      run: |
        cd nginx-1.26.2
        ./configure --add-dynamic-module=../ --with-compat --with-cc-opt="-Wno-error=pointer-sign"
        make modules
        ls -l objs/*.so
        file objs/*.so

    - name: Run unit tests
      run: |
        cd tests/unit
        gcc -o test_module test_module.c -I. -lcheck -lpthread -lrt -lm -lsubunit
        ./test_module